name: Run Skillyard Checks

on:
  workflow_dispatch:

jobs:
  setup-skillyard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Download Skillyard test repository
        run: |
          curl https://github.com/skillyard-io/tests/archive/refs/heads/main.zip -o skillyard-io-tests.zip
          ls -la
          sudo apt-get install unzip
          unzip file.zip -d skillyard-io-tests
          ls -la
