name: Run Skillyard Checks

on:
  workflow_dispatch:

jobs:
  setup-skillyard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Download Skillyard test repository
        run: |
          curl https://github.com/skillyard-io/tests/archive/refs/heads/main.zip -o skillyard-io-tests.zip
          sudo apt-get install unzip
          ls -la
          unzip ./skillyard-io-tests.zip -d skillyard-io-tests
          ls -la
      - name: Setup Skillyard tests repository
        run: |
          cd skillyard-io-tests/react-frontend-engineer/stages/fundamentals-of-web-technologies/contentful-customer-registration-portal
          yarn
          yarn playwright install --with-deps
          yarn playwright test
