name: Run skillyard checks

on:
  workflow_dispatch:

jobs:
  setup-skillyard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v3
        with:
         repository: skillyard-io/tests
         path: skillyard-io-tests
      - name: Checkout user submission repository
        uses: actions/checkout@v3
      - name: Install node v18.12.0 
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Setup Skillyard tests repository
        run: |
          ls -la ../
          ls -la ../../
          cd skillyard-io-tests/react-frontend-engineer/stages/fundamentals-of-web-technologies/contentful-customer-registration-portal
          yarn
          yarn playwright install --with-deps
          yarn playwright test
